[package]
name = "app"
version = "0.1.0"
authors = ["Jack Greenbaum <j.greenbaum@computer.org>", "Tyler Hall <tylerwhall@gmail.com>"]
repository = "https://github.com/tylerwhall/zephyr-rust.git"
edition = "2018"

[dependencies]
zephyr-sys = { path = "../../rust/zephyr-sys" }
zephyr-core = { path = "../../rust/zephyr-core" }
zephyr-macros = { path = "../../rust/zephyr-macros" }
