name: Container Build

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  containers:
    strategy:
      matrix:
        zephyr_version: [3.7.0, 2.7.3, 2.3.0]
    runs-on: ubuntu-latest
    env:
      ZEPHYR_VERSION: ${{ matrix.zephyr_version }}
      RUST_VERSION: 1.70.0

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=zephyr-rust:${{ env.ZEPHYR_VERSION }}-${{ env.RUST_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ci
          push: true
          file: ci/Dockerfile.zephyr
          build-args: |
            ZEPHYR_VERSION=${{ env.ZEPHYR_VERSION }}
            RUST_VERSION=${{ env.RUST_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
