name: Build

on:
  workflow_dispatch:
  push:
    branches:
      master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zephyr_version: [3.4.0, 2.7.3, 2.6.0, 2.5.0, 2.4.0, 2.3.0]
        board: [qemu_x86, qemu_cortex_m3, qemu_cortex_r5, native_posix, qemu_riscv32, qemu_riscv64]
        test: [samples/rust-app, samples/serial]
        exclude:
          - board: qemu_riscv32
            zephyr_version: 2.3.0
          - board: qemu_riscv64
            zephyr_version: 2.3.0
          - board: qemu_riscv32
            zephyr_version: 2.4.0
          - board: qemu_riscv64
            zephyr_version: 2.4.0
          - board: qemu_riscv32
            zephyr_version: 2.5.0
          - board: qemu_riscv64
            zephyr_version: 2.5.0
          - board: qemu_riscv32
            zephyr_version: 2.6.0
          - board: qemu_riscv64
            zephyr_version: 2.6.0
          - board: qemu_riscv32
            zephyr_version: 2.7.3
          - board: qemu_riscv64
            zephyr_version: 2.7.3
          - board: native_posix
            test: samples/serial
        include:
          - fails: false
          - run: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:zephyr-rust-${{ matrix.zephyr_version }}-1.68.0
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          west build -d /tmp/build -p auto -b ${{ matrix.board }} ${{ matrix.test }}

      - name: Run
        if: ${{ matrix.run }}
        run: |
          cd /tmp/build
          ninja run || ${{ matrix.fails }}
